# Generated by Django 5.0.2 on 2024-03-04 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_appointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.TextField(default='disi'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='2020-05-22'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(default='disi', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(default='disi', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='abc@mail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='disi', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(default='0123456789', max_length=50),
        ),
    ]
