# Generated by Django 5.0.2 on 2024-03-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0006_alter_appointment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='abc@gmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(default='Type anything'),
        ),
    ]
